require("./main.css");
import "../js/api.js";
import "../js/bootstrap.min.js";
import "../js/easing.js";
import "../js/genres_api.js";
import "../js/jquery-2.1.4.min.js";
import "../js/jquery.flexslider.js";
import "../js/jquery.magnific-popup.js";
import "../js/jquery.slidey.js";
import "../js/move-top.js";
import "./owl.carousel.js";
import "./simplePlayer.js";
import "./css/index.css";
