name: client

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: List directory contents
        run: ls -lah

      - name: Change to project directory
        run: cd festival

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: festival/node_modules  
          key: ${{ runner.OS }}-build-${{ hashFiles('festival/**/package-lock.json') }}  # festival 디렉토리 내부의 package-lock.json을 참조
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install Dependencies
        run: |
          cd festival
          npm install

      - name: Build
        run: |
          cd festival
          parcel build index.html --no-minify

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync \
            --region ap-northeast-2 \
            build s3://sa-team11.shop \ 
            --delete
